---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fringe
  labels:
    k8s-app: fringe
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: fringe
  template:
    metadata:
      labels:
        k8s-app: fringe
        name: fringe
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: alexandreponte/fringe
        name: fringe
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512M"
---
kind: Service
apiVersion: v1
metadata:
  name: fringe
spec:
  selector:
    k8s-app: fringe
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: LoadBalancer

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress
#   annotations:
#     kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#   - host: fringe.raj.ninja
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: fringe
#             port:
#               number: 80
